# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-pre-2
yarn_mappings=
loader_version=0.18.4
# Mod Properties
mod_version = 1.0.3
maven_group = daniking
archives_base_name = birdsnests
# Dependencies
fabric_version=0.143.14+26.1
cloth_config_version=21.11.153